ALTER TABLE "Course" ADD COLUMN "manifest" JSONB;
ALTER TABLE "Course" ADD COLUMN "manifestValid" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Course" ADD COLUMN "manifestErrors" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "Course" ADD COLUMN "deploymentStatus" TEXT NOT NULL DEFAULT 'NOT_UPLOADED';
ALTER TABLE "Course" ADD COLUMN "deploymentMessage" TEXT;
ALTER TABLE "Course" ADD COLUMN "nodePort" INTEGER;
ALTER TABLE "Course" ADD COLUMN "uploadedAt" TIMESTAMP(3);
ALTER TABLE "Course" ADD COLUMN "deployedAt" TIMESTAMP(3);
